export enum AuthActions {
  SET_AUTH_DATA = 'SET_AUTH_DATA',
  REMOVE_AUTH_DATA = 'REMOVE_AUTH_DATA',
  SET_SIGN_IN = 'SET_SIGN_IN',
  SET_SIGN_OUT = 'SET_SIGN_OUT',
  SET_SIGN_OUT_WITHOUT_REDIRECT = 'SET_SIGN_OUT_WITHOUT_REDIRECT',
}
